---
exclude_paths:
- "tests"
- 'templates'
- 'gulpfile.js'
- 'react/**.js'
- '**/index.js'
engines:
  scss-lint:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.sass"
  - "**.js"
  - "**.md"
