// flow-typed signature: 99200f6763d62e721dfa0c0700c80c65
// flow-typed version: <<STUB>>/@google/maps_v^0.4.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google/maps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google/maps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google/maps/bin/run' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/directions' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/distance-matrix' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/elevation' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/geocode' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/geolocation' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/places' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/roads' {
  declare module.exports: any;
}

declare module '@google/maps/lib/apis/timezone' {
  declare module.exports: any;
}

declare module '@google/maps/lib/index' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/attempt' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/circular-buffer' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/cli' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/convert' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/make-api-call' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/make-url-request' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/task' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/throttled-queue' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/validate' {
  declare module.exports: any;
}

declare module '@google/maps/lib/internal/wait' {
  declare module.exports: any;
}

declare module '@google/maps/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google/maps/bin/run.js' {
  declare module.exports: $Exports<'@google/maps/bin/run'>;
}
declare module '@google/maps/lib/apis/directions.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/directions'>;
}
declare module '@google/maps/lib/apis/distance-matrix.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/distance-matrix'>;
}
declare module '@google/maps/lib/apis/elevation.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/elevation'>;
}
declare module '@google/maps/lib/apis/geocode.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/geocode'>;
}
declare module '@google/maps/lib/apis/geolocation.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/geolocation'>;
}
declare module '@google/maps/lib/apis/places.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/places'>;
}
declare module '@google/maps/lib/apis/roads.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/roads'>;
}
declare module '@google/maps/lib/apis/timezone.js' {
  declare module.exports: $Exports<'@google/maps/lib/apis/timezone'>;
}
declare module '@google/maps/lib/index.js' {
  declare module.exports: $Exports<'@google/maps/lib/index'>;
}
declare module '@google/maps/lib/internal/attempt.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/attempt'>;
}
declare module '@google/maps/lib/internal/circular-buffer.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/circular-buffer'>;
}
declare module '@google/maps/lib/internal/cli.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/cli'>;
}
declare module '@google/maps/lib/internal/convert.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/convert'>;
}
declare module '@google/maps/lib/internal/make-api-call.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/make-api-call'>;
}
declare module '@google/maps/lib/internal/make-url-request.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/make-url-request'>;
}
declare module '@google/maps/lib/internal/task.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/task'>;
}
declare module '@google/maps/lib/internal/throttled-queue.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/throttled-queue'>;
}
declare module '@google/maps/lib/internal/validate.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/validate'>;
}
declare module '@google/maps/lib/internal/wait.js' {
  declare module.exports: $Exports<'@google/maps/lib/internal/wait'>;
}
declare module '@google/maps/lib/version.js' {
  declare module.exports: $Exports<'@google/maps/lib/version'>;
}
