---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: laundree-${BRANCH}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: laundree-${BRANCH}
    spec:
      containers:
      # [START web]
      - name: laundree
        image: laundree/laundree:${TAG}
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: 'REDIS_HOST'
            value: 'redis'
          - name: 'REDIS_PORT'
            value: '6379'
          - name: 'NODE_ENV'
            value: 'production'
          - name: 'MONGO_URL'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: mongoUrl
          - name: 'HOST'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: host
          - name: FACEBOOK_APP_ID
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: facebookAppId
          - name: 'FACEBOOK_APP_SECRET'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: facebookAppSecret
          - name: 'FACEBOOK_CALLBACK_URL'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: facebookCallbackUrl
          - name: 'GOOGLE_TRACKING_ID'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: googleTrackingId
          - name: 'GOOGLE_CALLBACK_URL'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: googleCallbackUrl
          - name: 'GOOGLE_CLIENT_API_KEY'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: googleClientApiKey
          - name: 'GOOGLE_CLIENT_ID'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: googleClientId
          - name: 'GOOGLE_CLIENT_SECRET'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: googleClientSecret
          - name: 'GOOGLE_SERVER_API_KEY'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: googleServerApiKey
          - name: 'MAILGUN_API_KEY'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: mailgunApiKey
          - name: 'ONE_SIGNAL_APP_ID'
            value: '390e23c3-658b-46cd-83ee-2fdead3211af'
          - name: 'ONE_SIGNAL_REST_API_KEY'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: oneSignalRestApiKey
          - name: 'OPBEAT_APP_ID'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: opbeatAppId
          - name: 'OPBEAT_ORGANIZATION_ID'
            valueFrom:
              configMapKeyRef:
                name: laundree-${BRANCH}
                key: opbeatOrgId
          - name: 'OPBEAT_SECRET_TOKEN'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: opbeatSecretToken
          - name: 'SESSION_SECRET'
            valueFrom:
              secretKeyRef:
                name: laundree-${BRANCH}
                key: sessionSecret
        ports:
          - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: laundree-${BRANCH}
  labels:
    app: laundree-${BRANCH}
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: laundree-${BRANCH}
