// flow-typed signature: 152318834fb23f730972159cf6dff6c9
// flow-typed version: <<STUB>>/base64url_v2.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64url' {
  declare module.exports: {
    toBuffer(base64: string): Buffer,
    encode(input: string | Buffer, encoding?: string) : string
  }
}
