// flow-typed signature: 03d6b32ecdbcb4c61878fba2f6368c2a
// flow-typed version: <<STUB>>/blob-to-buffer_v^1.2.6/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blob-to-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blob-to-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blob-to-buffer/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blob-to-buffer/index' {
  declare module.exports: $Exports<'blob-to-buffer'>;
}
declare module 'blob-to-buffer/index.js' {
  declare module.exports: $Exports<'blob-to-buffer'>;
}
declare module 'blob-to-buffer/test/basic.js' {
  declare module.exports: $Exports<'blob-to-buffer/test/basic'>;
}
