// flow-typed signature: 9c753d03578d50a7e7211475b1738614
// flow-typed version: <<STUB>>/chai-things_v^0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-things'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-things' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-things/lib/chai-things' {
  declare module.exports: any;
}

declare module 'chai-things/test/lib/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-things/lib/chai-things.js' {
  declare module.exports: $Exports<'chai-things/lib/chai-things'>;
}
declare module 'chai-things/test/lib/setup.js' {
  declare module.exports: $Exports<'chai-things/test/lib/setup'>;
}
