// flow-typed signature: ba92b9ee484334ac1e0613c665c22f75
// flow-typed version: <<STUB>>/config_v^1.26.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'config/defer' {
  declare module.exports: any;
}

declare module 'config/lib/config' {
  declare module.exports: any;
}

declare module 'config/raw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'config/defer.js' {
  declare module.exports: $Exports<'config/defer'>;
}
declare module 'config/lib/config.js' {
  declare module.exports: $Exports<'config/lib/config'>;
}
declare module 'config/raw.js' {
  declare module.exports: $Exports<'config/raw'>;
}
