// flow-typed signature: 31f0698779f7ddfc9279f737ce19f889
// flow-typed version: <<STUB>>/connect-flash_v^0.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-flash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-flash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-flash/lib/flash' {
  declare module.exports: any;
}

declare module 'connect-flash/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-flash/lib/flash.js' {
  declare module.exports: $Exports<'connect-flash/lib/flash'>;
}
declare module 'connect-flash/lib/index.js' {
  declare module.exports: $Exports<'connect-flash/lib/index'>;
}
