// flow-typed signature: 561e35b22dabc2b727a55b1f4ebae80b
// flow-typed version: <<STUB>>/detect-node_v^2.0.3/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'detect-node/index' {
  declare module.exports: $Exports<'detect-node'>;
}
declare module 'detect-node/index.js' {
  declare module.exports: $Exports<'detect-node'>;
}
