// flow-typed signature: f0edb35b5c6cc7998b62841721f4cb64
// flow-typed version: <<STUB>>/email-templates_v^2.3.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'email-templates'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'email-templates' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'email-templates/examples/handlebars_i18n/index' {
  declare module.exports: any;
}

declare module 'email-templates/examples/handlebars/index' {
  declare module.exports: any;
}

declare module 'email-templates/examples/inheritance/index' {
  declare module.exports: any;
}

declare module 'email-templates/examples/kuemailer/index' {
  declare module.exports: any;
}

declare module 'email-templates/examples/nodemailer/index' {
  declare module.exports: any;
}

declare module 'email-templates/examples/postmark/index' {
  declare module.exports: any;
}

declare module 'email-templates/lib/email-template' {
  declare module.exports: any;
}

declare module 'email-templates/lib/main' {
  declare module.exports: any;
}

declare module 'email-templates/lib/template-manager' {
  declare module.exports: any;
}

declare module 'email-templates/lib/util' {
  declare module.exports: any;
}

declare module 'email-templates/src/email-template' {
  declare module.exports: any;
}

declare module 'email-templates/src/main' {
  declare module.exports: any;
}

declare module 'email-templates/src/template-manager' {
  declare module.exports: any;
}

declare module 'email-templates/src/util' {
  declare module.exports: any;
}

declare module 'email-templates/test/testEmailTemplate' {
  declare module.exports: any;
}

declare module 'email-templates/test/testMain' {
  declare module.exports: any;
}

declare module 'email-templates/test/testTemplateManager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'email-templates/examples/handlebars_i18n/index.js' {
  declare module.exports: $Exports<'email-templates/examples/handlebars_i18n/index'>;
}
declare module 'email-templates/examples/handlebars/index.js' {
  declare module.exports: $Exports<'email-templates/examples/handlebars/index'>;
}
declare module 'email-templates/examples/inheritance/index.js' {
  declare module.exports: $Exports<'email-templates/examples/inheritance/index'>;
}
declare module 'email-templates/examples/kuemailer/index.js' {
  declare module.exports: $Exports<'email-templates/examples/kuemailer/index'>;
}
declare module 'email-templates/examples/nodemailer/index.js' {
  declare module.exports: $Exports<'email-templates/examples/nodemailer/index'>;
}
declare module 'email-templates/examples/postmark/index.js' {
  declare module.exports: $Exports<'email-templates/examples/postmark/index'>;
}
declare module 'email-templates/index' {
  declare module.exports: $Exports<'email-templates'>;
}
declare module 'email-templates/index.js' {
  declare module.exports: $Exports<'email-templates'>;
}
declare module 'email-templates/lib/email-template.js' {
  declare module.exports: $Exports<'email-templates/lib/email-template'>;
}
declare module 'email-templates/lib/main.js' {
  declare module.exports: $Exports<'email-templates/lib/main'>;
}
declare module 'email-templates/lib/template-manager.js' {
  declare module.exports: $Exports<'email-templates/lib/template-manager'>;
}
declare module 'email-templates/lib/util.js' {
  declare module.exports: $Exports<'email-templates/lib/util'>;
}
declare module 'email-templates/src/email-template.js' {
  declare module.exports: $Exports<'email-templates/src/email-template'>;
}
declare module 'email-templates/src/main.js' {
  declare module.exports: $Exports<'email-templates/src/main'>;
}
declare module 'email-templates/src/template-manager.js' {
  declare module.exports: $Exports<'email-templates/src/template-manager'>;
}
declare module 'email-templates/src/util.js' {
  declare module.exports: $Exports<'email-templates/src/util'>;
}
declare module 'email-templates/test/testEmailTemplate.js' {
  declare module.exports: $Exports<'email-templates/test/testEmailTemplate'>;
}
declare module 'email-templates/test/testMain.js' {
  declare module.exports: $Exports<'email-templates/test/testMain'>;
}
declare module 'email-templates/test/testTemplateManager.js' {
  declare module.exports: $Exports<'email-templates/test/testTemplateManager'>;
}
