// flow-typed signature: 88a9b7f3d11258e865e8a3804d9cea4d
// flow-typed version: <<STUB>>/gulp-coverage_v^0.3.38/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-coverage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-coverage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-coverage/contrib/cover' {
  declare module.exports: any;
}

declare module 'gulp-coverage/contrib/coverage_store' {
  declare module.exports: any;
}

declare module 'gulp-coverage/contrib/reporters/html' {
  declare module.exports: any;
}

declare module 'gulp-coverage/contrib/reporters/json' {
  declare module.exports: any;
}

declare module 'gulp-coverage/contrib/reporters/lcov' {
  declare module.exports: any;
}

declare module 'gulp-coverage/contrib/templates/instrumentation_header' {
  declare module.exports: any;
}

declare module 'gulp-coverage/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-coverage/test/cover' {
  declare module.exports: any;
}

declare module 'gulp-coverage/test/gulp-coverage' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/c2_cov' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/c2_test' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/chain' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/chainable' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/myModule' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/rewire' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/src' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/src2' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/src3' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/src4' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/srcchain' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/srcjasmine' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/test' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/test2' {
  declare module.exports: any;
}

declare module 'gulp-coverage/testsupport/test3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-coverage/contrib/cover.js' {
  declare module.exports: $Exports<'gulp-coverage/contrib/cover'>;
}
declare module 'gulp-coverage/contrib/coverage_store.js' {
  declare module.exports: $Exports<'gulp-coverage/contrib/coverage_store'>;
}
declare module 'gulp-coverage/contrib/reporters/html.js' {
  declare module.exports: $Exports<'gulp-coverage/contrib/reporters/html'>;
}
declare module 'gulp-coverage/contrib/reporters/json.js' {
  declare module.exports: $Exports<'gulp-coverage/contrib/reporters/json'>;
}
declare module 'gulp-coverage/contrib/reporters/lcov.js' {
  declare module.exports: $Exports<'gulp-coverage/contrib/reporters/lcov'>;
}
declare module 'gulp-coverage/contrib/templates/instrumentation_header.js' {
  declare module.exports: $Exports<'gulp-coverage/contrib/templates/instrumentation_header'>;
}
declare module 'gulp-coverage/gulpfile.js' {
  declare module.exports: $Exports<'gulp-coverage/gulpfile'>;
}
declare module 'gulp-coverage/index' {
  declare module.exports: $Exports<'gulp-coverage'>;
}
declare module 'gulp-coverage/index.js' {
  declare module.exports: $Exports<'gulp-coverage'>;
}
declare module 'gulp-coverage/test/cover.js' {
  declare module.exports: $Exports<'gulp-coverage/test/cover'>;
}
declare module 'gulp-coverage/test/gulp-coverage.js' {
  declare module.exports: $Exports<'gulp-coverage/test/gulp-coverage'>;
}
declare module 'gulp-coverage/testsupport/c2_cov.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/c2_cov'>;
}
declare module 'gulp-coverage/testsupport/c2_test.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/c2_test'>;
}
declare module 'gulp-coverage/testsupport/chain.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/chain'>;
}
declare module 'gulp-coverage/testsupport/chainable.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/chainable'>;
}
declare module 'gulp-coverage/testsupport/myModule.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/myModule'>;
}
declare module 'gulp-coverage/testsupport/rewire.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/rewire'>;
}
declare module 'gulp-coverage/testsupport/src.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/src'>;
}
declare module 'gulp-coverage/testsupport/src2.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/src2'>;
}
declare module 'gulp-coverage/testsupport/src3.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/src3'>;
}
declare module 'gulp-coverage/testsupport/src4.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/src4'>;
}
declare module 'gulp-coverage/testsupport/srcchain.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/srcchain'>;
}
declare module 'gulp-coverage/testsupport/srcjasmine.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/srcjasmine'>;
}
declare module 'gulp-coverage/testsupport/test.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/test'>;
}
declare module 'gulp-coverage/testsupport/test2.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/test2'>;
}
declare module 'gulp-coverage/testsupport/test3.js' {
  declare module.exports: $Exports<'gulp-coverage/testsupport/test3'>;
}
