// flow-typed signature: dfb746dea4d24af94a363c56d7ebb4e4
// flow-typed version: <<STUB>>/gulp-inject-modules_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-inject-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-inject-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-inject-modules/index' {
  declare module.exports: $Exports<'gulp-inject-modules'>;
}
declare module 'gulp-inject-modules/index.js' {
  declare module.exports: $Exports<'gulp-inject-modules'>;
}
