// flow-typed signature: 5862a607ca0911c300149e21ae756324
// flow-typed version: <<STUB>>/gulp-eslint_v^3.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-eslint/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-eslint/index' {
  declare module.exports: $Exports<'gulp-eslint'>;
}
declare module 'gulp-eslint/index.js' {
  declare module.exports: $Exports<'gulp-eslint'>;
}
declare module 'gulp-eslint/util.js' {
  declare module.exports: $Exports<'gulp-eslint/util'>;
}
