// flow-typed signature: 6f006cb603d69148ac41a8aa21070c19
// flow-typed version: <<STUB>>/gulp-babel-istanbul_v^1.3.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-babel-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-babel-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-babel-istanbul/test/fixtures/lib/add' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/test/fixtures/lib/multiply' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/test/fixtures/lib/subtract' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/test/fixtures/test/add' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/test/fixtures/test/subtract' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/test/main' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/test/threshold-checker' {
  declare module.exports: any;
}

declare module 'gulp-babel-istanbul/threshold-checker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-babel-istanbul/index' {
  declare module.exports: $Exports<'gulp-babel-istanbul'>;
}
declare module 'gulp-babel-istanbul/index.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul'>;
}
declare module 'gulp-babel-istanbul/test/fixtures/lib/add.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/fixtures/lib/add'>;
}
declare module 'gulp-babel-istanbul/test/fixtures/lib/multiply.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/fixtures/lib/multiply'>;
}
declare module 'gulp-babel-istanbul/test/fixtures/lib/subtract.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/fixtures/lib/subtract'>;
}
declare module 'gulp-babel-istanbul/test/fixtures/test/add.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/fixtures/test/add'>;
}
declare module 'gulp-babel-istanbul/test/fixtures/test/subtract.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/fixtures/test/subtract'>;
}
declare module 'gulp-babel-istanbul/test/main.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/main'>;
}
declare module 'gulp-babel-istanbul/test/threshold-checker.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/test/threshold-checker'>;
}
declare module 'gulp-babel-istanbul/threshold-checker.js' {
  declare module.exports: $Exports<'gulp-babel-istanbul/threshold-checker'>;
}
