// flow-typed signature: e44828d0b92d68b655d4d17954970c21
// flow-typed version: <<STUB>>/gulp-mocha_v^3.0.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-mocha/index' {
  declare module.exports: $Exports<'gulp-mocha'>;
}
declare module 'gulp-mocha/index.js' {
  declare module.exports: $Exports<'gulp-mocha'>;
}
