// flow-typed signature: 07abfe3a3aea4e8fdbb03a301f7633df
// flow-typed version: <<STUB>>/gulp-env_v^0.4.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-env/test/mock-env-module' {
  declare module.exports: any;
}

declare module 'gulp-env/test/test-gulp-env' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-env/index' {
  declare module.exports: $Exports<'gulp-env'>;
}
declare module 'gulp-env/index.js' {
  declare module.exports: $Exports<'gulp-env'>;
}
declare module 'gulp-env/test/mock-env-module.js' {
  declare module.exports: $Exports<'gulp-env/test/mock-env-module'>;
}
declare module 'gulp-env/test/test-gulp-env.js' {
  declare module.exports: $Exports<'gulp-env/test/test-gulp-env'>;
}
