// flow-typed signature: bf4abe30f836139b5a4a7e77db8d6566
// flow-typed version: <<STUB>>/jdenticon_v^1.7.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jdenticon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jdenticon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jdenticon/dist/jdenticon' {
  declare module.exports: any;
}

declare module 'jdenticon/dist/jdenticon.min' {
  declare module.exports: any;
}

declare module 'jdenticon/src/canvasRenderer' {
  declare module.exports: any;
}

declare module 'jdenticon/src/color' {
  declare module.exports: any;
}

declare module 'jdenticon/src/colorTheme' {
  declare module.exports: any;
}

declare module 'jdenticon/src/graphics' {
  declare module.exports: any;
}

declare module 'jdenticon/src/iconGenerator' {
  declare module.exports: any;
}

declare module 'jdenticon/src/jdenticon' {
  declare module.exports: any;
}

declare module 'jdenticon/src/point' {
  declare module.exports: any;
}

declare module 'jdenticon/src/sha1' {
  declare module.exports: any;
}

declare module 'jdenticon/src/shapes' {
  declare module.exports: any;
}

declare module 'jdenticon/src/svgElement' {
  declare module.exports: any;
}

declare module 'jdenticon/src/svgPath' {
  declare module.exports: any;
}

declare module 'jdenticon/src/svgRenderer' {
  declare module.exports: any;
}

declare module 'jdenticon/src/svgWriter' {
  declare module.exports: any;
}

declare module 'jdenticon/src/transform' {
  declare module.exports: any;
}

declare module 'jdenticon/test/sha1' {
  declare module.exports: any;
}

declare module 'jdenticon/test/toPng' {
  declare module.exports: any;
}

declare module 'jdenticon/test/toSvg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jdenticon/dist/jdenticon.js' {
  declare module.exports: $Exports<'jdenticon/dist/jdenticon'>;
}
declare module 'jdenticon/dist/jdenticon.min.js' {
  declare module.exports: $Exports<'jdenticon/dist/jdenticon.min'>;
}
declare module 'jdenticon/index' {
  declare module.exports: $Exports<'jdenticon'>;
}
declare module 'jdenticon/index.js' {
  declare module.exports: $Exports<'jdenticon'>;
}
declare module 'jdenticon/src/canvasRenderer.js' {
  declare module.exports: $Exports<'jdenticon/src/canvasRenderer'>;
}
declare module 'jdenticon/src/color.js' {
  declare module.exports: $Exports<'jdenticon/src/color'>;
}
declare module 'jdenticon/src/colorTheme.js' {
  declare module.exports: $Exports<'jdenticon/src/colorTheme'>;
}
declare module 'jdenticon/src/graphics.js' {
  declare module.exports: $Exports<'jdenticon/src/graphics'>;
}
declare module 'jdenticon/src/iconGenerator.js' {
  declare module.exports: $Exports<'jdenticon/src/iconGenerator'>;
}
declare module 'jdenticon/src/jdenticon.js' {
  declare module.exports: $Exports<'jdenticon/src/jdenticon'>;
}
declare module 'jdenticon/src/point.js' {
  declare module.exports: $Exports<'jdenticon/src/point'>;
}
declare module 'jdenticon/src/sha1.js' {
  declare module.exports: $Exports<'jdenticon/src/sha1'>;
}
declare module 'jdenticon/src/shapes.js' {
  declare module.exports: $Exports<'jdenticon/src/shapes'>;
}
declare module 'jdenticon/src/svgElement.js' {
  declare module.exports: $Exports<'jdenticon/src/svgElement'>;
}
declare module 'jdenticon/src/svgPath.js' {
  declare module.exports: $Exports<'jdenticon/src/svgPath'>;
}
declare module 'jdenticon/src/svgRenderer.js' {
  declare module.exports: $Exports<'jdenticon/src/svgRenderer'>;
}
declare module 'jdenticon/src/svgWriter.js' {
  declare module.exports: $Exports<'jdenticon/src/svgWriter'>;
}
declare module 'jdenticon/src/transform.js' {
  declare module.exports: $Exports<'jdenticon/src/transform'>;
}
declare module 'jdenticon/test/sha1.js' {
  declare module.exports: $Exports<'jdenticon/test/sha1'>;
}
declare module 'jdenticon/test/toPng.js' {
  declare module.exports: $Exports<'jdenticon/test/toPng'>;
}
declare module 'jdenticon/test/toSvg.js' {
  declare module.exports: $Exports<'jdenticon/test/toSvg'>;
}
