// flow-typed signature: f3e060bd75dc3cb147542742e8e03d77
// flow-typed version: <<STUB>>/jdenticon_v^1.3.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jdenticon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jdenticon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jdenticon/dist/jdenticon' {
  declare module.exports: any;
}

declare module 'jdenticon/dist/jdenticon.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jdenticon/dist/jdenticon.js' {
  declare module.exports: $Exports<'jdenticon/dist/jdenticon'>;
}
declare module 'jdenticon/dist/jdenticon.min.js' {
  declare module.exports: $Exports<'jdenticon/dist/jdenticon.min'>;
}
