// flow-typed signature: 932b2811ddb083aaf66bb07c2bd0f0cf
// flow-typed version: <<STUB>>/laundree-sdk_v0.0.23/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'laundree-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'laundree-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'laundree-sdk/src/redux/actions' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/redux/index' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/redux/reducers/helpers' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/redux/reducers/index' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/redux/reducers/userBookings' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/sdk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'laundree-sdk/index' {
  declare module.exports: $Exports<'laundree-sdk'>;
}
declare module 'laundree-sdk/index.js' {
  declare module.exports: $Exports<'laundree-sdk'>;
}
declare module 'laundree-sdk/src/redux/actions.js' {
  declare module.exports: $Exports<'laundree-sdk/src/redux/actions'>;
}
declare module 'laundree-sdk/src/redux/index.js' {
  declare module.exports: $Exports<'laundree-sdk/src/redux/index'>;
}
declare module 'laundree-sdk/src/redux/reducers/helpers.js' {
  declare module.exports: $Exports<'laundree-sdk/src/redux/reducers/helpers'>;
}
declare module 'laundree-sdk/src/redux/reducers/index.js' {
  declare module.exports: $Exports<'laundree-sdk/src/redux/reducers/index'>;
}
declare module 'laundree-sdk/src/redux/reducers/userBookings.js' {
  declare module.exports: $Exports<'laundree-sdk/src/redux/reducers/userBookings'>;
}
declare module 'laundree-sdk/src/sdk.js' {
  declare module.exports: $Exports<'laundree-sdk/src/sdk'>;
}
