// flow-typed signature: 5475aa51620715771283bccd3a798de6
// flow-typed version: <<STUB>>/laundree-sdk_v0.0.23/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'laundree-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'laundree-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'laundree-sdk/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/eslint-config-standard-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/flow-typed/npm/superagent_vx.x.x' {
  declare module.exports: any;
}

declare module 'laundree-sdk/lib/index' {
  declare module.exports: any;
}

declare module 'laundree-sdk/lib/redux' {
  declare module.exports: any;
}

declare module 'laundree-sdk/lib/sdk' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/index' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/redux' {
  declare module.exports: any;
}

declare module 'laundree-sdk/src/sdk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'laundree-sdk/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/eslint-config-standard_vx.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/eslint-config-standard-flow_vx.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/eslint-config-standard-flow_vx.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/eslint-plugin-standard_vx.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'laundree-sdk/flow-typed/npm/superagent_vx.x.x.js' {
  declare module.exports: $Exports<'laundree-sdk/flow-typed/npm/superagent_vx.x.x'>;
}
declare module 'laundree-sdk/lib/index.js' {
  declare module.exports: $Exports<'laundree-sdk/lib/index'>;
}
declare module 'laundree-sdk/lib/redux.js' {
  declare module.exports: $Exports<'laundree-sdk/lib/redux'>;
}
declare module 'laundree-sdk/lib/sdk.js' {
  declare module.exports: $Exports<'laundree-sdk/lib/sdk'>;
}
declare module 'laundree-sdk/src/index.js' {
  declare module.exports: $Exports<'laundree-sdk/src/index'>;
}
declare module 'laundree-sdk/src/redux.js' {
  declare module.exports: $Exports<'laundree-sdk/src/redux'>;
}
declare module 'laundree-sdk/src/sdk.js' {
  declare module.exports: $Exports<'laundree-sdk/src/sdk'>;
}
