// flow-typed signature: c145ef1abefee169465508c37000e6f0
// flow-typed version: <<STUB>>/locale_v^0.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'locale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'locale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'locale/examples/express' {
  declare module.exports: any;
}

declare module 'locale/examples/http' {
  declare module.exports: any;
}

declare module 'locale/lib/index' {
  declare module.exports: any;
}

declare module 'locale/lib/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'locale/examples/express.js' {
  declare module.exports: $Exports<'locale/examples/express'>;
}
declare module 'locale/examples/http.js' {
  declare module.exports: $Exports<'locale/examples/http'>;
}
declare module 'locale/lib/index.js' {
  declare module.exports: $Exports<'locale/lib/index'>;
}
declare module 'locale/lib/test.js' {
  declare module.exports: $Exports<'locale/lib/test'>;
}
