// flow-typed signature: 777b3562a8c5c82b22e79411b52f3a2c
// flow-typed version: <<STUB>>/mailgun-js_v^0.11.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailgun-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailgun-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailgun-js/lib/attachment' {
  declare module.exports: any;
}

declare module 'mailgun-js/lib/build' {
  declare module.exports: any;
}

declare module 'mailgun-js/lib/mailgun' {
  declare module.exports: any;
}

declare module 'mailgun-js/lib/request' {
  declare module.exports: any;
}

declare module 'mailgun-js/lib/schema' {
  declare module.exports: any;
}

declare module 'mailgun-js/test/mailgun.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailgun-js/lib/attachment.js' {
  declare module.exports: $Exports<'mailgun-js/lib/attachment'>;
}
declare module 'mailgun-js/lib/build.js' {
  declare module.exports: $Exports<'mailgun-js/lib/build'>;
}
declare module 'mailgun-js/lib/mailgun.js' {
  declare module.exports: $Exports<'mailgun-js/lib/mailgun'>;
}
declare module 'mailgun-js/lib/request.js' {
  declare module.exports: $Exports<'mailgun-js/lib/request'>;
}
declare module 'mailgun-js/lib/schema.js' {
  declare module.exports: $Exports<'mailgun-js/lib/schema'>;
}
declare module 'mailgun-js/test/mailgun.test.js' {
  declare module.exports: $Exports<'mailgun-js/test/mailgun.test'>;
}
