// flow-typed signature: 7c2399ffa509cf3696d421bc55c4bb32
// flow-typed version: <<STUB>>/nodemailer-stub-transport_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemailer-stub-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemailer-stub-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemailer-stub-transport/Gruntfile' {
  declare module.exports: any;
}

declare module 'nodemailer-stub-transport/src/stub-transport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemailer-stub-transport/Gruntfile.js' {
  declare module.exports: $Exports<'nodemailer-stub-transport/Gruntfile'>;
}
declare module 'nodemailer-stub-transport/src/stub-transport.js' {
  declare module.exports: $Exports<'nodemailer-stub-transport/src/stub-transport'>;
}
