// flow-typed signature: 1819c49b062d6e31de58710d1e0496f7
// flow-typed version: <<STUB>>/node-sass-middleware_v^0.11.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass-middleware/middleware' {
  declare module.exports: any;
}

declare module 'node-sass-middleware/test/fixtures/example-server' {
  declare module.exports: any;
}

declare module 'node-sass-middleware/test/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-sass-middleware/middleware.js' {
  declare module.exports: $Exports<'node-sass-middleware/middleware'>;
}
declare module 'node-sass-middleware/test/fixtures/example-server.js' {
  declare module.exports: $Exports<'node-sass-middleware/test/fixtures/example-server'>;
}
declare module 'node-sass-middleware/test/middleware.js' {
  declare module.exports: $Exports<'node-sass-middleware/test/middleware'>;
}
