// flow-typed signature: 1a1e3c845a5b801048e960d76bdcf70b
// flow-typed version: <<STUB>>/opbeat_v^4.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opbeat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'opbeat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opbeat/lib/agent' {
  declare module.exports: any;
}

declare module 'opbeat/lib/config' {
  declare module.exports: any;
}

declare module 'opbeat/lib/filters' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/async-hooks' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/express-utils' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/http-shared' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/index' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/bluebird' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/express-graphql' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/express' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/generic-pool' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/graphql' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/hapi' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/http' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/https' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/ioredis' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/knex' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/koa-router' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/mongodb-core' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/mysql' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/pg' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/redis' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/modules/ws' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/protocol' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/queue' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/shimmer' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/trace' {
  declare module.exports: any;
}

declare module 'opbeat/lib/instrumentation/transaction' {
  declare module.exports: any;
}

declare module 'opbeat/lib/logger' {
  declare module.exports: any;
}

declare module 'opbeat/lib/middleware/connect' {
  declare module.exports: any;
}

declare module 'opbeat/lib/parsers' {
  declare module.exports: any;
}

declare module 'opbeat/lib/request' {
  declare module.exports: any;
}

declare module 'opbeat/start' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opbeat/index' {
  declare module.exports: $Exports<'opbeat'>;
}
declare module 'opbeat/index.js' {
  declare module.exports: $Exports<'opbeat'>;
}
declare module 'opbeat/lib/agent.js' {
  declare module.exports: $Exports<'opbeat/lib/agent'>;
}
declare module 'opbeat/lib/config.js' {
  declare module.exports: $Exports<'opbeat/lib/config'>;
}
declare module 'opbeat/lib/filters.js' {
  declare module.exports: $Exports<'opbeat/lib/filters'>;
}
declare module 'opbeat/lib/instrumentation/async-hooks.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/async-hooks'>;
}
declare module 'opbeat/lib/instrumentation/express-utils.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/express-utils'>;
}
declare module 'opbeat/lib/instrumentation/http-shared.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/http-shared'>;
}
declare module 'opbeat/lib/instrumentation/index.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/index'>;
}
declare module 'opbeat/lib/instrumentation/modules/bluebird.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/bluebird'>;
}
declare module 'opbeat/lib/instrumentation/modules/express-graphql.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/express-graphql'>;
}
declare module 'opbeat/lib/instrumentation/modules/express.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/express'>;
}
declare module 'opbeat/lib/instrumentation/modules/generic-pool.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/generic-pool'>;
}
declare module 'opbeat/lib/instrumentation/modules/graphql.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/graphql'>;
}
declare module 'opbeat/lib/instrumentation/modules/hapi.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/hapi'>;
}
declare module 'opbeat/lib/instrumentation/modules/http.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/http'>;
}
declare module 'opbeat/lib/instrumentation/modules/https.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/https'>;
}
declare module 'opbeat/lib/instrumentation/modules/ioredis.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/ioredis'>;
}
declare module 'opbeat/lib/instrumentation/modules/knex.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/knex'>;
}
declare module 'opbeat/lib/instrumentation/modules/koa-router.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/koa-router'>;
}
declare module 'opbeat/lib/instrumentation/modules/mongodb-core.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/mongodb-core'>;
}
declare module 'opbeat/lib/instrumentation/modules/mysql.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/mysql'>;
}
declare module 'opbeat/lib/instrumentation/modules/pg.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/pg'>;
}
declare module 'opbeat/lib/instrumentation/modules/redis.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/redis'>;
}
declare module 'opbeat/lib/instrumentation/modules/ws.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/modules/ws'>;
}
declare module 'opbeat/lib/instrumentation/protocol.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/protocol'>;
}
declare module 'opbeat/lib/instrumentation/queue.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/queue'>;
}
declare module 'opbeat/lib/instrumentation/shimmer.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/shimmer'>;
}
declare module 'opbeat/lib/instrumentation/trace.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/trace'>;
}
declare module 'opbeat/lib/instrumentation/transaction.js' {
  declare module.exports: $Exports<'opbeat/lib/instrumentation/transaction'>;
}
declare module 'opbeat/lib/logger.js' {
  declare module.exports: $Exports<'opbeat/lib/logger'>;
}
declare module 'opbeat/lib/middleware/connect.js' {
  declare module.exports: $Exports<'opbeat/lib/middleware/connect'>;
}
declare module 'opbeat/lib/parsers.js' {
  declare module.exports: $Exports<'opbeat/lib/parsers'>;
}
declare module 'opbeat/lib/request.js' {
  declare module.exports: $Exports<'opbeat/lib/request'>;
}
declare module 'opbeat/start.js' {
  declare module.exports: $Exports<'opbeat/start'>;
}
