// flow-typed signature: 3e5843c9940219e22570d4b8d14c1598
// flow-typed version: <<STUB>>/passport-http_v^0.3.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-http/lib/passport-http/index' {
  declare module.exports: any;
}

declare module 'passport-http/lib/passport-http/strategies/basic' {
  declare module.exports: any;
}

declare module 'passport-http/lib/passport-http/strategies/digest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-http/lib/passport-http/index.js' {
  declare module.exports: $Exports<'passport-http/lib/passport-http/index'>;
}
declare module 'passport-http/lib/passport-http/strategies/basic.js' {
  declare module.exports: $Exports<'passport-http/lib/passport-http/strategies/basic'>;
}
declare module 'passport-http/lib/passport-http/strategies/digest.js' {
  declare module.exports: $Exports<'passport-http/lib/passport-http/strategies/digest'>;
}
