// flow-typed signature: 3242f5d971e709c8752d82c0853c57fa
// flow-typed version: <<STUB>>/passport-google-oauth_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-google-oauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-google-oauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-google-oauth/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-google-oauth/lib/index.js' {
  declare module.exports: $Exports<'passport-google-oauth/lib/index'>;
}
