// flow-typed signature: b96e111264bd3ae8e3a7097e05307c82
// flow-typed version: <<STUB>>/pdfkit_v^0.8.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfkit/js/data' {
  declare module.exports: any;
}

declare module 'pdfkit/js/document' {
  declare module.exports: any;
}

declare module 'pdfkit/js/font' {
  declare module.exports: any;
}

declare module 'pdfkit/js/font/afm' {
  declare module.exports: any;
}

declare module 'pdfkit/js/font/embedded' {
  declare module.exports: any;
}

declare module 'pdfkit/js/font/standard' {
  declare module.exports: any;
}

declare module 'pdfkit/js/gradient' {
  declare module.exports: any;
}

declare module 'pdfkit/js/image' {
  declare module.exports: any;
}

declare module 'pdfkit/js/image/jpeg' {
  declare module.exports: any;
}

declare module 'pdfkit/js/image/png' {
  declare module.exports: any;
}

declare module 'pdfkit/js/line_wrapper' {
  declare module.exports: any;
}

declare module 'pdfkit/js/mixins/annotations' {
  declare module.exports: any;
}

declare module 'pdfkit/js/mixins/color' {
  declare module.exports: any;
}

declare module 'pdfkit/js/mixins/fonts' {
  declare module.exports: any;
}

declare module 'pdfkit/js/mixins/images' {
  declare module.exports: any;
}

declare module 'pdfkit/js/mixins/text' {
  declare module.exports: any;
}

declare module 'pdfkit/js/mixins/vector' {
  declare module.exports: any;
}

declare module 'pdfkit/js/object' {
  declare module.exports: any;
}

declare module 'pdfkit/js/page' {
  declare module.exports: any;
}

declare module 'pdfkit/js/path' {
  declare module.exports: any;
}

declare module 'pdfkit/js/reference' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfkit/js/data.js' {
  declare module.exports: $Exports<'pdfkit/js/data'>;
}
declare module 'pdfkit/js/document.js' {
  declare module.exports: $Exports<'pdfkit/js/document'>;
}
declare module 'pdfkit/js/font.js' {
  declare module.exports: $Exports<'pdfkit/js/font'>;
}
declare module 'pdfkit/js/font/afm.js' {
  declare module.exports: $Exports<'pdfkit/js/font/afm'>;
}
declare module 'pdfkit/js/font/embedded.js' {
  declare module.exports: $Exports<'pdfkit/js/font/embedded'>;
}
declare module 'pdfkit/js/font/standard.js' {
  declare module.exports: $Exports<'pdfkit/js/font/standard'>;
}
declare module 'pdfkit/js/gradient.js' {
  declare module.exports: $Exports<'pdfkit/js/gradient'>;
}
declare module 'pdfkit/js/image.js' {
  declare module.exports: $Exports<'pdfkit/js/image'>;
}
declare module 'pdfkit/js/image/jpeg.js' {
  declare module.exports: $Exports<'pdfkit/js/image/jpeg'>;
}
declare module 'pdfkit/js/image/png.js' {
  declare module.exports: $Exports<'pdfkit/js/image/png'>;
}
declare module 'pdfkit/js/line_wrapper.js' {
  declare module.exports: $Exports<'pdfkit/js/line_wrapper'>;
}
declare module 'pdfkit/js/mixins/annotations.js' {
  declare module.exports: $Exports<'pdfkit/js/mixins/annotations'>;
}
declare module 'pdfkit/js/mixins/color.js' {
  declare module.exports: $Exports<'pdfkit/js/mixins/color'>;
}
declare module 'pdfkit/js/mixins/fonts.js' {
  declare module.exports: $Exports<'pdfkit/js/mixins/fonts'>;
}
declare module 'pdfkit/js/mixins/images.js' {
  declare module.exports: $Exports<'pdfkit/js/mixins/images'>;
}
declare module 'pdfkit/js/mixins/text.js' {
  declare module.exports: $Exports<'pdfkit/js/mixins/text'>;
}
declare module 'pdfkit/js/mixins/vector.js' {
  declare module.exports: $Exports<'pdfkit/js/mixins/vector'>;
}
declare module 'pdfkit/js/object.js' {
  declare module.exports: $Exports<'pdfkit/js/object'>;
}
declare module 'pdfkit/js/page.js' {
  declare module.exports: $Exports<'pdfkit/js/page'>;
}
declare module 'pdfkit/js/path.js' {
  declare module.exports: $Exports<'pdfkit/js/path'>;
}
declare module 'pdfkit/js/reference.js' {
  declare module.exports: $Exports<'pdfkit/js/reference'>;
}
