// flow-typed signature: d9e98b018a78ab48bc9638c083675606
// flow-typed version: <<STUB>>/redux-actions_v^2.0.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare type reduxActions$Action<T, A, M> = {
  payload: A,
  type: T,
  meta: M
}

declare type reduxActions$ActionError<T, M> = {
  error: true,
  payload: Error,
  type: T,
  meta: M
}
declare type reduxActions$PayloadCreator<A, B> = (A) => B

declare type reduxActions$MetaCreator<A, M> = (A) => M

declare type reduxActions$ActionCreator<T, A, B, M> = (A) => reduxActions$Action<T, A, M>

declare type reduxActions$ActionCreatorError<T, B, M> = (Error) => reduxActions$ActionError<T, M>

declare module 'redux-actions' {
  declare export function createAction<T, A, B, M> (type: T, payloadCreator?: reduxActions$PayloadCreator<A, B>, metaCreator?: reduxActions$MetaCreator<A, M>): reduxActions$ActionCreator<T, A, B, M> & reduxActions$ActionCreatorError<T, B, M>
}
