// flow-typed signature: b519e389a6509fe341f4ad9555ecd3dc
// flow-typed version: <<STUB>>/sauce-connect-launcher_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sauce-connect-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sauce-connect-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sauce-connect-launcher/examples/example' {
  declare module.exports: any;
}

declare module 'sauce-connect-launcher/Gruntfile' {
  declare module.exports: any;
}

declare module 'sauce-connect-launcher/lib/process_options' {
  declare module.exports: any;
}

declare module 'sauce-connect-launcher/lib/sauce-connect-launcher' {
  declare module.exports: any;
}

declare module 'sauce-connect-launcher/lib/try_run' {
  declare module.exports: any;
}

declare module 'sauce-connect-launcher/scripts/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sauce-connect-launcher/examples/example.js' {
  declare module.exports: $Exports<'sauce-connect-launcher/examples/example'>;
}
declare module 'sauce-connect-launcher/Gruntfile.js' {
  declare module.exports: $Exports<'sauce-connect-launcher/Gruntfile'>;
}
declare module 'sauce-connect-launcher/index' {
  declare module.exports: $Exports<'sauce-connect-launcher'>;
}
declare module 'sauce-connect-launcher/index.js' {
  declare module.exports: $Exports<'sauce-connect-launcher'>;
}
declare module 'sauce-connect-launcher/lib/process_options.js' {
  declare module.exports: $Exports<'sauce-connect-launcher/lib/process_options'>;
}
declare module 'sauce-connect-launcher/lib/sauce-connect-launcher.js' {
  declare module.exports: $Exports<'sauce-connect-launcher/lib/sauce-connect-launcher'>;
}
declare module 'sauce-connect-launcher/lib/try_run.js' {
  declare module.exports: $Exports<'sauce-connect-launcher/lib/try_run'>;
}
declare module 'sauce-connect-launcher/scripts/install.js' {
  declare module.exports: $Exports<'sauce-connect-launcher/scripts/install'>;
}
