// flow-typed signature: f16253e0034b4cbb856449c59f40809b
// flow-typed version: <<STUB>>/swagger-tools_v^0.10.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swagger-tools/lib/helpers' {
  declare module.exports: any;
}

declare module 'swagger-tools/lib/specs' {
  declare module.exports: any;
}

declare module 'swagger-tools/lib/validators' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/helpers' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-metadata' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-router' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-security' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/en' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/es' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/fr' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/it' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/ja' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/pl' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/pt' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/ru' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/tr' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/translator' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lang/zh-cn' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/backbone-min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/handlebars-2.0.0' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/highlight.7.3.pack' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/jquery-1.8.0.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/jquery.ba-bbq.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/jquery.slideto.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/jquery.wiggle.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/js-yaml.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/jsoneditor.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/lodash.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/marked' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/lib/swagger-oauth' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/swagger-ui' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-ui/swagger-ui.min' {
  declare module.exports: any;
}

declare module 'swagger-tools/middleware/swagger-validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swagger-tools/index' {
  declare module.exports: $Exports<'swagger-tools'>;
}
declare module 'swagger-tools/index.js' {
  declare module.exports: $Exports<'swagger-tools'>;
}
declare module 'swagger-tools/lib/helpers.js' {
  declare module.exports: $Exports<'swagger-tools/lib/helpers'>;
}
declare module 'swagger-tools/lib/specs.js' {
  declare module.exports: $Exports<'swagger-tools/lib/specs'>;
}
declare module 'swagger-tools/lib/validators.js' {
  declare module.exports: $Exports<'swagger-tools/lib/validators'>;
}
declare module 'swagger-tools/middleware/helpers.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/helpers'>;
}
declare module 'swagger-tools/middleware/swagger-metadata.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-metadata'>;
}
declare module 'swagger-tools/middleware/swagger-router.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-router'>;
}
declare module 'swagger-tools/middleware/swagger-security.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-security'>;
}
declare module 'swagger-tools/middleware/swagger-ui.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/en.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/en'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/es.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/es'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/fr.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/fr'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/it.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/it'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/ja.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/ja'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/pl.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/pl'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/pt.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/pt'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/ru.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/ru'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/tr.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/tr'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/translator.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/translator'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lang/zh-cn.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lang/zh-cn'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/backbone-min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/backbone-min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/handlebars-2.0.0.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/handlebars-2.0.0'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/highlight.7.3.pack.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/highlight.7.3.pack'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/jquery-1.8.0.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/jquery-1.8.0.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/jquery.ba-bbq.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/jquery.ba-bbq.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/jquery.slideto.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/jquery.slideto.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/jquery.wiggle.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/jquery.wiggle.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/js-yaml.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/js-yaml.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/jsoneditor.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/jsoneditor.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/lodash.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/lodash.min'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/marked.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/marked'>;
}
declare module 'swagger-tools/middleware/swagger-ui/lib/swagger-oauth.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/lib/swagger-oauth'>;
}
declare module 'swagger-tools/middleware/swagger-ui/swagger-ui.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/swagger-ui'>;
}
declare module 'swagger-tools/middleware/swagger-ui/swagger-ui.min.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-ui/swagger-ui.min'>;
}
declare module 'swagger-tools/middleware/swagger-validator.js' {
  declare module.exports: $Exports<'swagger-tools/middleware/swagger-validator'>;
}
