// flow-typed signature: ed683a91159eaac7eaa30e297fdb437f
// flow-typed version: <<STUB>>/urlsafe-base64_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urlsafe-base64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'urlsafe-base64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urlsafe-base64/lib/urlsafe-base64' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urlsafe-base64/index' {
  declare module.exports: $Exports<'urlsafe-base64'>;
}
declare module 'urlsafe-base64/index.js' {
  declare module.exports: $Exports<'urlsafe-base64'>;
}
declare module 'urlsafe-base64/lib/urlsafe-base64.js' {
  declare module.exports: $Exports<'urlsafe-base64/lib/urlsafe-base64'>;
}
