sass:
  outputStyle: 'compressed'

opbeat:
  trackRelease: true
  enable: true

logging:
  http:
    enabled: true
    format: 'common'
  error:
    enabled: true

session:
  domain: 'laundree.io'
  secure: true
