sass:
  outputStyle: 'compressed'

opbeat:
  trackRelease: true
  enable: true

google:
  trackingId: UA-97847799-1

logging:
  http:
    enabled: true
    format: 'common'
  error:
    enabled: true
