mongo:
  url: 'mongodb://localhost/laundree-test'

logging:
  http:
    enabled: false

security:
  password:
    saltRounds: 1
google:
  trackingId: ''

oneSignal:
  enabled: false

defaultUsers:
  test-admin@example.com: admin

mailgun:
  enabled: false
